Dedup stylesheet href
Stranger6667/css-inline pull request #90
Opened 2020-10-30 16:49 UTC by sbeckeriv

Dearest Maintainer,

First thank you for your work on this project. I am comparing this to
the Roadie gem for ruby. It inlines css into html emails. I have a
really fun email that keeps including a script tag. The same dup script
tag. I have updated your code to dedup the hrefs you are loading.

Thanks again. Your command line tool takes 3.1 seconds where the
Roadie gem takes about 2 minutes.

Dictated but not reviewed,
Becker

2020-10-30 17:34 UTC, sbeckeriv commented on src/lib.rs
> +                        .unwrap()
yes this need to handle it not being there.

2020-11-01 09:55 UTC, Stranger6667 requested changes
Hi @sbeckeriv

Cool! Thank you for your contribution :) I left some performance-related comments (minor ones, though)

2020-11-01 09:55 UTC, Stranger6667 commented on src/lib.rs
> +                })
I think we can avoid some allocations & `is_empty` check with `filter_map`:
```suggestion
                .filter_map(|link_tag| link_tag.attributes.borrow().get("href").map(str::to_string))
```

2020-11-01 09:55 UTC, Stranger6667 commented on src/lib.rs
> +            links.sort();
This one might be slightly faster

```suggestion
            links.sort_unstable();
```

2020-11-01 09:56 UTC, Stranger6667 commented
> Thanks again. Your command line tool takes 3.1 seconds where the
Roadie gem takes about 2 minutes.

Wow! That is great! :)

2020-11-01 20:22 UTC, Stranger6667 commented
I will merge it as is and then apply some performance tweaks :)

2020-11-01 20:22 UTC, merged

2020-11-01 22:46 UTC, sbeckeriv commented
Suggestions looks good. It has been a busy few days. Thanks for merging and applying. Should the node built be passing? I could not figure that out.

2020-11-01 22:52 UTC, Stranger6667 commented
> Should the node built be passing? I could not figure that out.

Yep, this one is quite strange, probably it might be caused by some WASM-related dependency updates, but the TypeScript tests pass, which is good enough to make a new release :) I'll look at the issue later